prompts = [
    # 0
"""
This homework requires that you have read and **programmed** along with:

- [cs171-lab8-preReading.pdf](https://www.cs171.org/Homework_instructions/week-08/lab/cs171-lab8-preReading.pdf) (under week 8 in the modules tab in canvas)
- [https://scotch.io/tutorials/demystifying-es6-classes-and-prototypal-inheritance](https://scotch.io/tutorials/demystifying-es6-classes-and-prototypal-inheritance) (explanation of JS ES6 Classes with more examples)

## 1) A survey about the diffusion of microfinance loans (10 points)

In this homework you will work with survey data on microfinance loans. Banerjee et al [1] collected the data in order to develop a model of information diffusion in social networks. To come right to the point: you don't need any knowledge or additional information on microfinance. We will only cover a very small part of the collected data to demonstrate you how to visualize survey results efficiently with JS and D3.

The authors of the study collected detailed demographic and network data in 75 villages in India, six months before a microfinance institution began offering their products to these villagers. The combination of the original survey, information about first-informed villagers and results of the subsequent participation made it possible to draw conclusions on the diffusion of information.

If you are interested in the study you can get the paper here: http://science.sciencemag.org/content/341/6144/1236498
[1] Banerjee, Abhijit, et al. "The diffusion of microfinance." *Science* (2013).

### Data

- **Household characteristics** has demographic information about a household's home (own or rent, electricity, number of rooms, latrine type, etc.)
- Individual characteristics with detailed demographic information (age, language skills, occupation, etc.) were collected for some households
- Extensive data about relationships between these households

*In this assignment you will only work with the household characteristics dataset. You will have to use the following columns:*

- ```survey```, this variable was generated by us. Imagine it is the date when the household was surveyed.
- ```ownrent```, if the home is owned, rented or given by government
- ```hohreligion```, religion they belong
- ```electricity```, whether the household has private/government/no electricity 
- ```latrine```, type of latrine (own/common/no) in the household

### Template

To help you get started with this homework assignment we have prepared a template that you can use. It is based on the front-end framework *Bootstrap* and it includes the JS libraries: *D3* and *jQuery*. Furthermore, a CSV file (```household_charateristics.csv```) is stored in the folder *"data"*.
These are the files in the template:
_#index.html#_
_#main.js#_
_#style.css#_

### Overview

In the last lab you have learned how to link multiple views with each other, how to make visualization components reusable and how to use D3's brush component to filter the data.

You should now apply what you have learned to create an interactive visualization with multiple views. Your final webpage should contain an area chart and several barcharts. Whenever the user changes the selection - via the brushing component in the area chart - all the bar charts should be updated accordingly.

### Implementation

1. **Specifiy the webpage layout**

	You should create a 2-column layout in HTML and CSS. The area chart with the time period filter should be in the left column and the bar charts should be in the right column. We have included *Bootstrap* in the template so that you can complete this task quickly.

Now print the index.html file.
""",

# 1
"""
## 1) A survey about the diffusion of microfinance loans (10 points)

In this homework you will work with survey data on microfinance loans. The authors of the study collected detailed demographic and network data in 75 villages in India, six months before a microfinance institution began offering their products to these villagers. The combination of the original survey, information about first-informed villagers and results of the subsequent participation made it possible to draw conclusions on the diffusion of information.

### Data

- **Household characteristics** has demographic information about a household's home (own or rent, electricity, number of rooms, latrine type, etc.)
- Individual characteristics with detailed demographic information (age, language skills, occupation, etc.) were collected for some households
- Extensive data about relationships between these households

*In this assignment you will only work with the household characteristics dataset. You will have to use the following columns:*

- ```survey```, this variable was generated by us. Imagine it is the date when the household was surveyed.
- ```ownrent```, if the home is owned, rented or given by government
- ```hohreligion```, religion they belong
- ```electricity```, whether the household has private/government/no electricity 
- ```latrine```, type of latrine (own/common/no) in the household

### Template

These are the files that you already created:
_#index.html#_
_#main.js#_
_#barchart.js#_
Furthermore, a CSV file (```household_charateristics.csv```) is stored in the folder *"data"*.

### Overview

In the last lab you have learned how to link multiple views with each other, how to make visualization components reusable and how to use D3's brush component to filter the data.

You should now apply what you have learned to create an interactive visualization with multiple views. Your final webpage should contain an area chart and several barcharts. Whenever the user changes the selection - via the brushing component in the area chart - all the bar charts should be updated accordingly.

### Implementation

Finish these steps.
4. **Load the CSV data and create the bar chart objects**

	We have already prepared a few code snippets to help you get started. Open the files ```main.js``` and ```barchart.js``` and get an overview.
	
	Similar to our last lab, you have to implement visualizations as reusable components. This is especially important if you want to use the same visualization type (e.g., bar charts) several times on the same webpage with different data in each visualization.

	The goal is to implement a generic bar chart object in ```barchart.js``` that can be used in ```main.js``` multiple times for these variables:
	
	-  ```ownrent```
	-  ```electricity```
	-  ```latrine```
	-  ```hohreligion```

	Example: You can find the values *Christianity*, *Hinduism* and *Islam* in the column ```hohreligion```. One of your bar charts should show how many households belong to which religion.
		
	Each bar chart should contain a title, a y-axis and labels for each bar.
		
	#### Grouping data with d3.group and d3.rollup
	
	D3 includes a powerful functionality to transform a flat data structure into a nested one. Prior version of d3 used ````d3.nest``` for this functionality, but d3 v6 replaced that with [```d3.group```](https://github.com/d3/d3-array/blob/master/README.md#group) and  [```d3.rollup()```](https://github.com/d3/d3-array/blob/master/README.md#rollup).  We would highly recommend you to use these function to prepare the data for your bar charts. 	**Example**
	
	*CSV-Data:*
	```
	student,city
	John,Boston
	Sarah,Boston
	Stacy,New York
	Anna,London
	Mike,Boston
	```
	
	First, let's use *d3.group()* to group the rows by *city*:
	
	```javascript
	let studentsByCity = d3.group(student,d=>d.city)
	```
	
	As a result we get a map structure:
	
	```javascript
	studentsByCity = 
		Map(3) {
 		 "Boston" => [
			{student: "John", city: "Boston" },
			{student: "Sarah", city: "Boston" },
			{student: "Mike", city: "Boston" }
		]
  		"New York" => [{student: "Stacy", city: "New York"}]
  		"London" => [{student: "Anna", city: "London"}]
	}
	
	```
		
	To convert a Map to an Array, use ```Array.from```. For example, if we want to produce an array of ```key``` , ```value``` pairs, we can use: 
	
	```javascript
	Array.from(d3.group(student,d=>d.city), ([key, value]) => ({key, value}))
	```
	
	We can use the ```d3.rollup()``` function to aggregate the values for each group (e.g. sum, count, avg):
	
	```javascript
	let countStudentsByCity = d3.rollup(student,leaves=>leaves.length,d=>d.city)
	```
	
	If we transform the outpt Map to an array of key values pairs, we get an array with the number of students for each city:
	
	```javascript
	countStudentsByCity = [
		{ key: "Boston", value: 3 },
		{ key: "New York", value: 1 },
		{ key: "London", value: 1 }
	];
	```

Now tell me how to update index.html, main.js, and barchart.js files in codes
""",

# 2
"""
## 1) A survey about the diffusion of microfinance loans (10 points)

In this homework you will work with survey data on microfinance loans. The authors of the study collected detailed demographic and network data in 75 villages in India, six months before a microfinance institution began offering their products to these villagers. The combination of the original survey, information about first-informed villagers and results of the subsequent participation made it possible to draw conclusions on the diffusion of information.

### Data

- **Household characteristics** has demographic information about a household's home (own or rent, electricity, number of rooms, latrine type, etc.)
- Individual characteristics with detailed demographic information (age, language skills, occupation, etc.) were collected for some households
- Extensive data about relationships between these households

*In this assignment you will only work with the household characteristics dataset. You will have to use the following columns:*

- ```survey```, this variable was generated by us. Imagine it is the date when the household was surveyed.
- ```ownrent```, if the home is owned, rented or given by government
- ```hohreligion```, religion they belong
- ```electricity```, whether the household has private/government/no electricity 
- ```latrine```, type of latrine (own/common/no) in the household

### Template

These are the files that you already created:
_#index.html#_
_#main.js#_
_#areachart.js#_
Furthermore, a CSV file (```household_charateristics.csv```) is stored in the folder *"data"*.

### Overview

In the last lab you have learned how to link multiple views with each other, how to make visualization components reusable and how to use D3's brush component to filter the data.

You should now apply what you have learned to create an interactive visualization with multiple views. Your final webpage should contain an area chart and several barcharts. Whenever the user changes the selection - via the brushing component in the area chart - all the bar charts should be updated accordingly.

### Implementation

5. **Implement the area chart**
Finish these steps.

	In the template we've given you code that draws an area chart. However, you'll need to wrangle the data for the visualization and add interactivity to the chart.

	The area chart should display the number of surveys that were conducted over time. Furthermore, it should enable the user to specify a desired time range which automatically influences the bar charts in the right column.

	1. Prepare the data in the ```wrangleData()``` function. You can use d3.rollup() again to count the number of surveys for each day. Make sure that you have the date variable stored as a date object and that the days are in correct order.
	2. Create an instance of the area chart class in `main.js`, passing in the data and the selector for the parent element you created in `index.html`
	3. Once done, an area chart should show up. Feel free to style the chart as you wish.

Now tell me how to update index.html, main.js, and areachart.js files in codes
""",

# 3
"""
## 1) A survey about the diffusion of microfinance loans (10 points)

In this homework you will work with survey data on microfinance loans. The authors of the study collected detailed demographic and network data in 75 villages in India, six months before a microfinance institution began offering their products to these villagers. The combination of the original survey, information about first-informed villagers and results of the subsequent participation made it possible to draw conclusions on the diffusion of information.

### Data

- **Household characteristics** has demographic information about a household's home (own or rent, electricity, number of rooms, latrine type, etc.)
- Individual characteristics with detailed demographic information (age, language skills, occupation, etc.) were collected for some households
- Extensive data about relationships between these households

*In this assignment you will only work with the household characteristics dataset. You will have to use the following columns:*

- ```survey```, this variable was generated by us. Imagine it is the date when the household was surveyed.
- ```ownrent```, if the home is owned, rented or given by government
- ```hohreligion```, religion they belong
- ```electricity```, whether the household has private/government/no electricity 
- ```latrine```, type of latrine (own/common/no) in the household

### Template

These are the files that you already created:
_#index.html#_
_#main.js#_
_#areachart.js#_
Furthermore, a CSV file (```household_charateristics.csv```) is stored in the folder *"data"*.

### Overview

In the last lab you have learned how to link multiple views with each other, how to make visualization components reusable and how to use D3's brush component to filter the data.

You should now apply what you have learned to create an interactive visualization with multiple views. Your final webpage should contain an area chart and several barcharts. Whenever the user changes the selection - via the brushing component in the area chart - all the bar charts should be updated accordingly.

### Implementation

Finish these steps. You are using D3 v7.

6. **Use a brushing component in your area chart as a time period filter**
	
	The idea of brushing is to allow the user to select a subset of data interactively. Changes are automatically reflected in the linked visualizations, which are the bar charts in our case.
	
	Initialize the brushing component (```d3.brushX()```) and append it to the drawing area. Whenever the user changes the selection, call the ```brushed()``` function in ```main.js```.

Now tell me how to update main.js and areachart.js in codes.
""",

# 4
"""
## 1) A survey about the diffusion of microfinance loans (10 points)

In this homework you will work with survey data on microfinance loans. The authors of the study collected detailed demographic and network data in 75 villages in India, six months before a microfinance institution began offering their products to these villagers. The combination of the original survey, information about first-informed villagers and results of the subsequent participation made it possible to draw conclusions on the diffusion of information.

### Data

- **Household characteristics** has demographic information about a household's home (own or rent, electricity, number of rooms, latrine type, etc.)
- Individual characteristics with detailed demographic information (age, language skills, occupation, etc.) were collected for some households
- Extensive data about relationships between these households

*In this assignment you will only work with the household characteristics dataset. You will have to use the following columns:*

- ```survey```, this variable was generated by us. Imagine it is the date when the household was surveyed.
- ```ownrent```, if the home is owned, rented or given by government
- ```hohreligion```, religion they belong
- ```electricity```, whether the household has private/government/no electricity 
- ```latrine```, type of latrine (own/common/no) in the household

### Template

These are the files that you already created:
_#index.html#_
_#main.js#_
_#barchart.js#_
Furthermore, a CSV file (```household_charateristics.csv```) is stored in the folder *"data"*.

### Overview

In the last lab you have learned how to link multiple views with each other, how to make visualization components reusable and how to use D3's brush component to filter the data.

You should now apply what you have learned to create an interactive visualization with multiple views. Your final webpage should contain an area chart and several barcharts. Whenever the user changes the selection - via the brushing component in the area chart - all the bar charts should be updated accordingly.

### Implementation

7. **Implement the ```brushed(d)``` function and connect it with the bar charts** Note that You are using D3 v7.

	Get the range of the selected region (start and end date) in the area chart and call the ```selectionChanged()``` function in all the linked bar charts.

Now tell me how to update main.js in codes.
""",

# 5
"""
## 1) A survey about the diffusion of microfinance loans (10 points)

In this homework you will work with survey data on microfinance loans. The authors of the study collected detailed demographic and network data in 75 villages in India, six months before a microfinance institution began offering their products to these villagers. The combination of the original survey, information about first-informed villagers and results of the subsequent participation made it possible to draw conclusions on the diffusion of information.

### Data

- **Household characteristics** has demographic information about a household's home (own or rent, electricity, number of rooms, latrine type, etc.)
- Individual characteristics with detailed demographic information (age, language skills, occupation, etc.) were collected for some households
- Extensive data about relationships between these households

*In this assignment you will only work with the household characteristics dataset. You will have to use the following columns:*

- ```survey```, this variable was generated by us. Imagine it is the date when the household was surveyed.
- ```ownrent```, if the home is owned, rented or given by government
- ```hohreligion```, religion they belong
- ```electricity```, whether the household has private/government/no electricity 
- ```latrine```, type of latrine (own/common/no) in the household

### Template

These are the files that you already created:
_#index.html#_
_#main.js#_
_#barchart.js#_
Furthermore, a CSV file (```household_charateristics.csv```) is stored in the folder *"data"*.

### Overview

In the last lab you have learned how to link multiple views with each other, how to make visualization components reusable and how to use D3's brush component to filter the data.

You should now apply what you have learned to create an interactive visualization with multiple views. Your final webpage should contain an area chart and several barcharts. Whenever the user changes the selection - via the brushing component in the area chart - all the bar charts should be updated accordingly.

### Implementation

8. **Use transitions to make changes smoother**

	Integrate D3's transitions into your bar charts (rectangles, labels).

Now tell me how to update barchart.js in codes.
""",

# 6
"""
## 1) A survey about the diffusion of microfinance loans (10 points)

In this homework you will work with survey data on microfinance loans. The authors of the study collected detailed demographic and network data in 75 villages in India, six months before a microfinance institution began offering their products to these villagers. The combination of the original survey, information about first-informed villagers and results of the subsequent participation made it possible to draw conclusions on the diffusion of information.

### Data

- **Household characteristics** has demographic information about a household's home (own or rent, electricity, number of rooms, latrine type, etc.)
- Individual characteristics with detailed demographic information (age, language skills, occupation, etc.) were collected for some households
- Extensive data about relationships between these households

*In this assignment you will only work with the household characteristics dataset. You will have to use the following columns:*

- ```survey```, this variable was generated by us. Imagine it is the date when the household was surveyed.
- ```ownrent```, if the home is owned, rented or given by government
- ```hohreligion```, religion they belong
- ```electricity```, whether the household has private/government/no electricity 
- ```latrine```, type of latrine (own/common/no) in the household

### Template

These are the files that you already created:
_#index.html#_
_#areachart.js#_
_#barchart.js#_
Furthermore, a CSV file (```household_charateristics.csv```) is stored in the folder *"data"*.

### Overview

In the last lab you have learned how to link multiple views with each other, how to make visualization components reusable and how to use D3's brush component to filter the data.

You should now apply what you have learned to create an interactive visualization with multiple views. Your final webpage should contain an area chart and several barcharts. Whenever the user changes the selection - via the brushing component in the area chart - all the bar charts should be updated accordingly.

### Implementation

9. **Make your webpage and your visualizations responsive**

    Until now, you have probably specified a fixed size for your SVG drawing areas every time. This is more convenient but actually far from ideal if you want to address users with different screen resolutions, which is our goal in most scenarios. 
	
	There are different ways of implementing more flexible visualizations. In our case, Bootstrap - a responsive, mobile-friendly front-end framework - makes it already very easy to create a responsive webpage, just by using the *fluid grid system* ([http://getbootstrap.com/css/#grid](http://getbootstrap.com/css/#grid)). You can use the grid classes to set up the page layout and to define at which point columns should wrap onto a new line.
	
	In addition, you can create your own CSS media queries to make individual adjustments (e.g. font size, spacings, ...) for different screen sizes. You can read more about it here: [https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries)

    You should now be able to display the area and bar charts below each other if the screen is not wide enough. But this doesn't solve the problem of the fixed-sized SVG areas, so you need one further extension. Whenever you initialize a new visualization you can check the width of the parent container and set the SVG width accordingly. The height can remain unchanged.

    *Example for getting the width of a div element with Javascript:*

    ```javascript
    document.getElementById('elementId').getBoundingClientRect().width
    ```

    Try this concept in your current webpage and make the visualizations more flexible!

Now tell me how to update index.html, barchart.js and areachart.js in codes. Dont print the whole file.
""",

# 7
"""
## 1) A survey about the diffusion of microfinance loans (10 points)

In this homework you will work with survey data on microfinance loans. The authors of the study collected detailed demographic and network data in 75 villages in India, six months before a microfinance institution began offering their products to these villagers. The combination of the original survey, information about first-informed villagers and results of the subsequent participation made it possible to draw conclusions on the diffusion of information.

### Data

- **Household characteristics** has demographic information about a household's home (own or rent, electricity, number of rooms, latrine type, etc.)
- Individual characteristics with detailed demographic information (age, language skills, occupation, etc.) were collected for some households
- Extensive data about relationships between these households

*In this assignment you will only work with the household characteristics dataset. You will have to use the following columns:*

- ```survey```, this variable was generated by us. Imagine it is the date when the household was surveyed.
- ```ownrent```, if the home is owned, rented or given by government
- ```hohreligion```, religion they belong
- ```electricity```, whether the household has private/government/no electricity 
- ```latrine```, type of latrine (own/common/no) in the household

### Template

These are the files that you already created:
_#index.html#_
_#style.css#_
_#areachart.js#_
_#barchart.js#_
Furthermore, a CSV file (```household_charateristics.csv```) is stored in the folder *"data"*.

### Overview

In the last lab you have learned how to link multiple views with each other, how to make visualization components reusable and how to use D3's brush component to filter the data.

You should now apply what you have learned to create an interactive visualization with multiple views. Your final webpage should contain an area chart and several barcharts. Whenever the user changes the selection - via the brushing component in the area chart - all the bar charts should be updated accordingly.

### Implementation
Finish this step:

10. **Create a proper style for your webpage**

	Maintain good spacing between UI components, overall layout, font size, color scheme, etc.

Now print the changes you made to style.css.
"""
]